name: Sync

on:
  push:
    branches:
      - main
## main test
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js v20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
      - name: Opening pull request
        id: pull
        uses: duckdum/sync-branches-gh@v1.7.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PULL_REQUEST_TITLE: Sync main with develop 
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          CONTENT_COMPARISON: true
