name: Sync

on:
  push:
    branches:
      - main
## main test
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Opening pull request
        id: pull
        uses: duckdum/sync-branches-gh@v1.8.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          PULL_REQUEST_BODY: "This is an automatic Pull Request to keep develop up to date with main."
          CONTENT_COMPARISON: true
          REVIEWERS: '["duckdum"]'
          